In [5]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt 
import seaborn as sns 
import statistics as sts 
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler,MinMaxScaler

In [6]:
#Data collection alst few monthns shravan data
dataFrame=pd.read_csv(r"C:\Shravan\PythonPratice\supervised\MyObservabilityQueue.csv",encoding_errors='ignore')

In [7]:
#data infomration
dataFrame.info()
dataFrame.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              607 non-null    int64
 1   Work Item Type  607 non-null    object
 2   Title           607 non-null    object
 3   Assigned To     607 non-null    object
 4   State           607 non-null    object
 5   Tags            555 non-null    object
 6   Created By      607 non-null    object
 7   Actual Time     266 non-null    float64
 8   Closed Status   0 non-null      float64
dtypes: float64(2), int64(1), object(6)
memory usage: 42.8+ KB

                 ID  Actual Time  Closed Status
count    607.000000   266.000000            0.0
mean   16153.566722     3.112782            NaN
std      929.694283     2.978613            NaN
min    13695.000000     0.000000            NaN
25%    15403.000000     1.000000            NaN
50%    16296.000000     2.000000            NaN
75%    16823.500000     4.000000            NaN
max    18029.000000    24.000000            NaN

In [9]:
#Missing and null values checks
dataFrame.isna().sum()

ID                  0
Work Item Type      0
Title               0
Assigned To         0
State               0
Tags               52
Created By          0
Actual Time       341
Closed Status     607
dtype: int64

In [11]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              607 non-null    int64
 1   Work Item Type  607 non-null    object
 2   Title           607 non-null    object
 3   Assigned To     607 non-null    object
 4   State           607 non-null    object
 5   Tags            555 non-null    object
 6   Created By      607 non-null    object
 7   Actual Time     266 non-null    float64
 8   Closed Status   0 non-null      float64
dtypes: float64(2), int64(1), object(6)
memory usage: 42.8+ KB

In [15]:
dataFrame['Actual Time'] = dataFrame['Actual Time'].fillna(dataFrame['Actual Time'].mean())

In [25]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              607 non-null    int64
 1   Work Item Type  607 non-null    object
 2   Title           607 non-null    object
 3   Assigned To     607 non-null    object
 4   State           607 non-null    object
 5   Created By      607 non-null    object
 6   Actual Time     607 non-null    float64
 7   Closed Status   607 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 38.1+ KB

In [24]:
dataFrame['Closed Status'] = dataFrame['Closed Status'].fillna('Completed')

In [20]:
drop_col=dataFrame.drop(columns=['Tags'],axis=1,inplace=True)

In [26]:
dataFrame.sample(10)

,ID,Work Item Type,Title,Assigned To,State,Created By,Actual Time,Closed Status
446,16805,Task,Data Verifications,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,4.000000,Completed
281,16159,Product Backlog Item,Servers Patching phase 3,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,3.112782,Completed
465,16834,Product Backlog Item,S25-SP16-> INC4246712 - NG-Access issues - res...,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,3.112782,Completed
200,15536,Product Backlog Item,RITM0605567 - Completed,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,3.112782,Completed
445,16804,Task,Support,Sayed Ulfath Hussain S Bellary <A9JB@it.eurofi...,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,4.000000,Completed
250,15844,Task,Support,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,6.000000,Completed
563,17578,Task,Support,Alluri Sreenivasulu <Y4UH@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,2.000000,Completed
366,16488,Task,Support,Binu Mathew <BLE8@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,0.000000,Completed
313,16336,Product Backlog Item,RE: Action Required for LB certificate update ...,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,3.112782,Completed
585,17771,Product Backlog Item,ITAAG012 || Certificate Expiry soon,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,Done,Pesala Shravan Kumar <X8NS@it.eurofinseu.com>,3.112782,Completed